services:
  - type: web
    name: offering-tracker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python index.py"
    envVars:
      - key: FLASK_ENV
        value: production
